apiVersion: v1
kind: Namespace
metadata:
  name: global
---
apiVersion: v1
kind: Secret
metadata:
  name: registry
  namespace: global
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXQuZWRlbmZhcm0uaWQ6NTA1MCI6IHsKCQkJImF1dGgiOiAiYkdsdVoyZHZPbnBDU2xwTldYRk9OVlJWT0ZaNlJ6YzRhRzloIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: global
  labels:
    app: global
  namespace: global
spec:
  replicas: 1
  selector:
    matchLabels:
      app: global
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: global
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - name: global
        image: git.edenfarm.id:5050/project-version3/erp-dashboard/global/dev:<VERSION>
        ports:
        - name: http-port
          containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: 50Mi
            cpu: 15m
          limits:
            memory: 150Mi
            cpu: 100m
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Jakarta
          type: File
          # tolerations:
          # - key: instance_type
          #   value: service
          #   effect: NoSchedule
          #   operator: Equal
          # affinity:
          #   nodeAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       nodeSelectorTerms:
          #       - matchExpressions:
          #         - key: role
          #           operator: In
          #           values:
          #           - devops
          #   podAntiAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #     - labelSelector:
          #         matchExpressions:
          #         - key: app
          #           operator: In
          #           values:
          #           - global
          #       topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: svc-global
  namespace: global
  labels:
    app: global
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-port
  selector:
    app: global
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-global
  namespace: global
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: global
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: global
  namespace: global
spec:
  dnsNames:
  - dev-global.edenfarm.tech
  secretName: dev-global-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: global
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: global
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dev-global.edenfarm.tech
    secretName: dev-global-tls
  rules:
  - host: dev-global.edenfarm.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-global
            port:
              number: 80
